services:
  postgres:
    image: postgres:15
    container_name: infobeer_db_container
    environment:
      POSTGRES_USER: userbeer
      POSTGRES_PASSWORD: passbeer
      POSTGRES_DB: beers_db
    ports:
      - "5432:5432"
    volumes:
      - infobeer_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    container_name: infobeer_backend_container
    environment:
      DB_USER: userbeer
      DB_PASSWORD: passbeer
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: beers_db
      SERVER_PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: infobeer_frontend_container
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  infobeer_data:
